#!/bin/php
<?php

use Solisty\CommandLine\CommandLine;
use Solisty\Main\Application;

require __DIR__ . "/vendor/autoload.php";

try {
    Application::create([
        "APP_BASE" => __DIR__,
    ], false, true);

    $cli = new CommandLine($argv);

    $cli->run();
} catch (Exception $ex) {
    echo $ex;
}
